from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(541, 294)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.labelTitle = QtWidgets.QLabel(self.centralwidget)
        self.labelTitle.setGeometry(QtCore.QRect(50, 0, 451, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.labelTitle.setFont(font)
        self.labelTitle.setObjectName("labelTitle")
        self.lineNum = QtWidgets.QLineEdit(self.centralwidget)
        self.lineNum.setGeometry(QtCore.QRect(200, 60, 131, 21))
        self.lineNum.setObjectName("lineNum")
        self.lineExp = QtWidgets.QLineEdit(self.centralwidget)
        self.lineExp.setGeometry(QtCore.QRect(200, 90, 131, 21))
        self.lineExp.setObjectName("lineExp")
        self.labelNum = QtWidgets.QLabel(self.centralwidget)
        self.labelNum.setGeometry(QtCore.QRect(50, 60, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.labelNum.setFont(font)
        self.labelNum.setObjectName("labelNum")
        self.labelExp = QtWidgets.QLabel(self.centralwidget)
        self.labelExp.setGeometry(QtCore.QRect(50, 90, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.labelExp.setFont(font)
        self.labelExp.setObjectName("labelExp")
        self.labelAns = QtWidgets.QLabel(self.centralwidget)
        self.labelAns.setGeometry(QtCore.QRect(140, 120, 291, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelAns.setFont(font)
        self.labelAns.setText("")
        self.labelAns.setObjectName("labelAns")
        self.buttonCalc = QtWidgets.QPushButton(self.centralwidget)
        self.buttonCalc.setGeometry(QtCore.QRect(400, 50, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.buttonCalc.setFont(font)
        self.buttonCalc.setObjectName("buttonCalc")
        self.buttonClear = QtWidgets.QPushButton(self.centralwidget)
        self.buttonClear.setGeometry(QtCore.QRect(400, 80, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.buttonClear.setFont(font)
        self.buttonClear.setObjectName("buttonClear")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(280, 180, 151, 151))
        self.label.setText("")
        self.label.setObjectName("label")
        self.labelCat = QtWidgets.QLabel(self.centralwidget)
        self.labelCat.setGeometry(QtCore.QRect(50, 180, 441, 71))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelCat.setFont(font)
        self.labelCat.setText("")
        self.labelCat.setObjectName("labelCat")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 541, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.labelTitle.setText(_translate("MainWindow", "Exponent Calculator and Cat Ear Counter"))
        self.labelNum.setText(_translate("MainWindow", "Enter base:"))
        self.labelExp.setText(_translate("MainWindow", "Enter exponent:"))
        self.buttonCalc.setText(_translate("MainWindow", "Calculate"))
        self.buttonClear.setText(_translate("MainWindow", "Clear"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
